<?php declare(strict_types=1);

# https://github.com/nette/di/blob/master/tests/DI/Compiler.generatedLocatorMulti.phpt
require __DIR__ . '/../bootstrap.php';


class Lorem
{
}

interface Locator
{
	public function getA(): Lorem;

	public function getB(): ?Lorem;

	public function createC(): Lorem;

	public function createD(): ?Lorem;
}

$configurator = new \NetteConfigurator();
$configurator->setTempDirectory(__DIR__ . '/temp');
$configurator->addConfig(__DIR__ . '/autogenerated.neon');

$container = $configurator->createContainer();


debug__printer(
	'Generované továrničky a service lokátory',
	[
		'createServiceLorem1',
		'createServiceOne',
		'createServiceTwo',
		'createServiceStd',
	]
);
